#!/bin/bash
### BEGIN INIT INFO
# Provides:          httpd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

DAEMON=/opt/httpd/bin/httpd
CONFIG=/opt/httpd/etc/httpd.conf

case "$1" in
  start)
  	$DAEMON -a start -f $CONFIG
  	rc=$?
  	;;
  stop)
  	$DAEMON -a stop -f $CONFIG
  	rc=$?
  	;;
  *)
    echo $"Usage: $0 {start|stop}"
    exit 2
esac

exit $rc
